"""External Accountability OTC skill exports."""

from .athena import Reader, StaticAthenaReader, execute_athena, latest_load_date, normalize_scalar, rows_payload
from .catalog import QUERY_ALIASES, QUERY_CATALOG, QUERY_KEYWORDS, load_catalog, compile_nl2sql_plan, render_semantic_sql, SemanticSQLPlan, query_catalog_rows, resolve_query_id
from .config import AccountabilitySettings
from .nl2sql_agent import BedrockNL2SQLPlanner, NL2SQLPlanner, StaticSemanticNL2SQLPlanner
from .prompts import (
    ACCOUNTABILITY_AGENT_EXAMPLES,
    ACCOUNTABILITY_AGENT_INSTRUCTIONS,
    ACCOUNTABILITY_EXPECTED_FREE_SQL,
    ACCOUNTABILITY_EXPECTED_NL2SQL,
    ACCOUNTABILITY_EXPECTED_TOOLS,
    ACCOUNTABILITY_EXPECTED_TOOLS_ANY,
    ACCOUNTABILITY_FREE_SQL_CATALOG_PROMPT,
    ACCOUNTABILITY_FREE_SQL_SQL,
    ACCOUNTABILITY_FREE_SQL_SQL_PROMPT,
    ACCOUNTABILITY_NL2SQL_PROMPT,
    ACCOUNTABILITY_TOOL_EXAMPLES,
    ACCOUNTABILITY_USER_PROMPT,
    AccountabilityPlan,
    ToolPlanStep,
    build_accountability_plan,
    free_sql_example,
)
from .runtime import compact_result, render_query_sql, run_catalog_query, run_free_sql, run_named_query, run_nl2sql
from .contracts import (
    ACCOUNTABILITY_FREE_SQL_SPEC,
    ACCOUNTABILITY_NL2SQL_SPEC,
    ACCOUNTABILITY_SKILL_AGENT_SPEC,
    ACCOUNTABILITY_SKILL_CONTRACTS,
    contract_policy_for_route,
    describe_contracts,
    lineage_goal_for_route,
    build_lineage_memory,
)
from .skill import AccountabilityOTCSkill, build_skill, make_tools
from .sql_safety import clean_load_date, limit_value, single_statement, validate_read_only_sql

from .environment import (
    build_skill_decision_environment,
    decision_cases,
    lineage_for_environment,
    make_skill_decision_transition,
    reward_skill_decision,
)

from .hardening import (
    AccountabilityDiagnostic,
    classify_live_error,
    diagnose_result,
    diagnostic_lineage,
    hardening_checklist,
    hardening_summary,
)

__all__ = [
    "hardening_summary",
    "hardening_checklist",
    "diagnostic_lineage",
    "diagnose_result",
    "classify_live_error",
    "AccountabilityDiagnostic",
    "ACCOUNTABILITY_AGENT_EXAMPLES",
    "ACCOUNTABILITY_AGENT_INSTRUCTIONS",
    "ACCOUNTABILITY_EXPECTED_FREE_SQL",
    "ACCOUNTABILITY_EXPECTED_NL2SQL",
    "ACCOUNTABILITY_EXPECTED_TOOLS_ANY",
    "ACCOUNTABILITY_FREE_SQL_CATALOG_PROMPT",
    "ACCOUNTABILITY_FREE_SQL_SQL",
    "ACCOUNTABILITY_FREE_SQL_SQL_PROMPT",
    "ACCOUNTABILITY_NL2SQL_PROMPT",
    "ACCOUNTABILITY_TOOL_EXAMPLES",
    "ACCOUNTABILITY_EXPECTED_TOOLS",
    "ACCOUNTABILITY_USER_PROMPT",
    "ACCOUNTABILITY_FREE_SQL_SPEC",
    "ACCOUNTABILITY_NL2SQL_SPEC",
    "ACCOUNTABILITY_SKILL_AGENT_SPEC",
    "ACCOUNTABILITY_SKILL_CONTRACTS",
    "AccountabilityOTCSkill",
    "AccountabilityPlan",
    "AccountabilitySettings",
    "QUERY_ALIASES",
    "QUERY_CATALOG",
    "QUERY_KEYWORDS",
    "Reader",
    "StaticAthenaReader",
    "BedrockNL2SQLPlanner",
    "NL2SQLPlanner",
    "StaticSemanticNL2SQLPlanner",
    "ToolPlanStep",
    "build_accountability_plan",
    "build_skill",
    "contract_policy_for_route",
    "describe_contracts",
    "lineage_goal_for_route",
    "build_lineage_memory",
    "clean_load_date",
    "compact_result",
    "execute_athena",
    "free_sql_example",
    "latest_load_date",
    "limit_value",
    "compile_nl2sql_plan",
    "render_semantic_sql",
    "SemanticSQLPlan",
    "load_catalog",
    "make_tools",
    "normalize_scalar",
    "query_catalog_rows",
    "render_query_sql",
    "resolve_query_id",
    "rows_payload",
    "run_catalog_query",
    "run_free_sql",
    "run_named_query",
    "run_nl2sql",
    "single_statement",
    "validate_read_only_sql",
    "build_skill_decision_environment",
    "decision_cases",
    "lineage_for_environment",
    "make_skill_decision_transition",
    "reward_skill_decision",
]
