"""Generate documentation and a notebook from the runtime API manifest."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import agentic_systems as toolkit  # noqa: E402

API_DOC = ROOT / "docs" / "API.md"
CONTRACT_DOC = ROOT / "docs" / "API_CONTRACT.md"
CONTRACT_NOTEBOOK = ROOT / "tutorials" / "api" / "14_api_contract_matrix.ipynb"
TUTORIAL_README = ROOT / "tutorials" / "README.md"


def _source_path(source: str) -> str:
    module = source.split(":", 1)[0]
    if not module.startswith("agentic_systems"):
        return module
    parts = module.split(".")[1:]
    suffix = "/".join(parts) + ".py" if parts else "__init__.py"
    return "src/agentic_systems/" + suffix


def _api_doc(original: str, manifest: dict[str, Any]) -> str:
    start_marker = "## Complete Public API Index"
    end_marker = "## Provider Conformance API"
    start = original.index(start_marker)
    end = original.index(end_marker, start)
    exports = [entry["id"] for entry in manifest["entries"] if entry["member"] is None]
    block = [
        start_marker,
        "",
        "This block is generated from `agentic_systems.api_contract()`.",
        "It is the exact stable top-level API; CI rejects any difference.",
        "",
        "```text",
        *exports,
        "```",
        "",
        f"Contract entries including public members: {manifest['entry_count']}",
        f"Shared contract scenarios: {manifest['scenario_count']}",
        "",
        f"Contract checksum: `{manifest['checksum']}`",
        "",
    ]
    return original[:start] + "\n".join(block) + original[end:]


def _contract_doc(manifest: dict[str, Any]) -> str:
    lines = [
        "# Agentic Systems 2.1 API Contract",
        "",
        "Generated by `scripts/generate_api_contract.py` from the runtime manifest.",
        "Do not edit this file by hand.",
        "",
        "## Contract Summary",
        "",
        f"- Schema: `{manifest['schema_version']}`",
        f"- Stable exports: `{manifest['export_count']}`",
        f"- Export and member IDs: `{manifest['entry_count']}`",
        f"- Shared scenarios: `{manifest['scenario_count']}`",
        f"- Checksum: `{manifest['checksum']}`",
        "- Notebook: `tutorials/api/14_api_contract_matrix.ipynb`",
        "",
        "## Traceability",
        "",
        "Every heading below is one canonical ID shared by Source, API,",
        "documentation, the reference notebook and pytest.",
        "",
    ]
    lines.extend(
        [
            "### Scenario registry",
            "",
            "| Scenario | Notebooks | API IDs |",
            "|---|---|---|",
        ]
    )
    for scenario in manifest["scenarios"]:
        lines.append(
            f"| `{scenario['id']}` | "
            f"{'<br>'.join(scenario['notebooks'])} | "
            f"{'<br>'.join(scenario['api_ids'])} |"
        )
    lines.extend(
        [
            "",
            "## API IDs",
            "",
        ]
    )

    for entry in manifest["entries"]:
        signature = entry["signature"] or "n/a"
        lines.extend(
            [
                f"## `{entry['id']}`",
                "",
                re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", entry["summary"]),
                "",
                f"- Export: `{entry['export']}`",
                f"- Member: `{entry['member'] or 'n/a'}`",
                f"- Kind: `{entry['kind']}`",
                f"- Tier: `{entry['tier']}`",
                f"- Signature: `{signature}`",
                f"- Source: `{_source_path(entry['source'])}` (`{entry['source']}`)",
                f"- Contract ID: `{entry['id']}`",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _md(source: str) -> dict[str, Any]:
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(True)}


def _code(source: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(True),
    }


def _notebook(manifest: dict[str, Any]) -> str:
    ids = json.dumps(manifest["ids"], indent=2)
    scenarios = json.dumps(
        [
            {
                "id": item["id"],
                "notebooks": item["notebooks"],
                "api_ids": item["api_ids"],
            }
            for item in manifest["scenarios"]
        ],
        indent=2,
    )
    cells = [
        _md(
            "# 14 - Contrato API 1:1 de Agentic Systems 2.1\n\n"
            "## Objetivo\n\n"
            "Verificar de forma ejecutable que Source, API, documentacion, "
            "notebooks y pytest comparten exactamente los mismos IDs publicos. "
            "Este capitulo cierra el recorrido iniciado por runtimes, tools, skills, "
            "agents, systems, environments y evals.\n"
            "\n\n**Lugar en el modelo:** este cap\u00edtulo no a\u00f1ade "
            "c\u00f3mputo; verifica que todas las superficies publicadas describen "
            "el mismo producto 2.0.\n\n"
            "**Evidencia exigida:** IDs, miembros, escenarios y checksum deben "
            "coincidir exactamente con Source y resolverse sin efectos externos.\n\n"
            "**L\u00edmite de la evidencia:** cobertura contractual prueba presencia "
            "y trazabilidad de API; las garant\u00edas de comportamiento provienen "
            "de los escenarios y tests ejecutables.\n"
        ),
        _md(
            "## Parametros de ejecucion\n\n"
            "Este notebook es determinista y offline: no usa credenciales ni llama "
            "modelos. La matriz live de providers/frameworks se valida antes.\n"
        ),
        _code(
            "import agentic_systems as toolkit\n\n"
            "api_coverage = [\n"
            "    'toolkit.api_contract',\n"
            "    'toolkit.exercise_api',\n"
            "    'toolkit.show',\n"
            "]\n"
        ),
        _md(
            "## Inventario esperado\n\n"
            "La lista se genera desde Source. Cambiar un export, miembro, firma o "
            "tipo publico exige regenerar y revisar este capitulo.\n"
        ),
        _code(
            "EXPECTED_API_IDS = tuple(" + ids + ")\n"
            f"EXPECTED_CHECKSUM = '{manifest['checksum']}'\n"
            "EXPECTED_SCENARIOS = tuple(" + scenarios + ")\n"
            "EXPECTED_SCENARIO_IDS = tuple(item['id'] for item in EXPECTED_SCENARIOS)\n"
            f"EXPECTED_SCENARIO_COUNT = {manifest['scenario_count']}\n"
            f"EXPECTED_EXPORT_COUNT = {manifest['export_count']}\n"
            f"EXPECTED_ENTRY_COUNT = {manifest['entry_count']}\n"
        ),
        _code(
            "manifest = toolkit.api_contract()\n"
            "assert tuple(manifest['ids']) == EXPECTED_API_IDS\n"
            "assert manifest['checksum'] == EXPECTED_CHECKSUM\n"
            "assert manifest['export_count'] == EXPECTED_EXPORT_COUNT\n"
            "assert manifest['entry_count'] == EXPECTED_ENTRY_COUNT\n"
            "public_scenarios = tuple(\n"
            "    {\n"
            "        'id': item['id'],\n"
            "        'notebooks': item['notebooks'],\n"
            "        'api_ids': item['api_ids'],\n"
            "    }\n"
            "    for item in manifest['scenarios']\n"
            ")\n"
            "assert public_scenarios == EXPECTED_SCENARIOS\n"
            "assert tuple(manifest['scenario_ids']) == EXPECTED_SCENARIO_IDS\n"
            "assert manifest['scenario_count'] == EXPECTED_SCENARIO_COUNT\n"
            "toolkit.show({key: manifest[key] for key in "
            "('schema_version', 'export_count', 'entry_count', 'scenario_count', 'checksum')})\n"
        ),
        _md(
            "## Ejercicio completo\n\n"
            "Se resuelven todos los simbolos, miembros, campos y firmas sin invocar "
            "constructores ni producir efectos externos.\n"
        ),
        _code(
            "exercise = toolkit.exercise_api()\n"
            "assert exercise['ok'] is True\n"
            "assert exercise['count'] == EXPECTED_ENTRY_COUNT\n"
            "assert tuple(item['id'] for item in exercise['results']) == EXPECTED_API_IDS\n"
            "toolkit.show({'ok': exercise['ok'], "
            "'verified_ids': exercise['count'], 'checksum': exercise['checksum']})\n"
        ),
        _md(
            "## Resultado e interpretacion\n\n"
            "El resultado valido reporta `ok=True` y el mismo numero de IDs que el "
            "manifiesto. Cualquier diferencia es drift contractual y bloquea la release.\n"
        ),
    ]
    for index, cell in enumerate(cells):
        cell["id"] = f"contract-{index:02d}"
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3"},
            "agentic_systems": {
                "layer": "api",
                "provider": "python-runtime",
                "framework": "native",
                "execution_mode": "offline",
                "api_coverage": [
                    "toolkit.api_contract",
                    "toolkit.exercise_api",
                    "toolkit.show",
                ],
                "curriculum_origin": "2.0",
                "curriculum_order": 20,
                "narrative_reviewed": "2.1.2",
                "expected_api_checksum": manifest["checksum"],
                "expected_api_entries": manifest["entry_count"],
                "expected_scenario_count": manifest["scenario_count"],
                "contract_scenarios": ["api_contract"],
                "expected_scenario_ids": manifest["scenario_ids"],
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"


def _tutorial_readme(manifest: dict[str, Any]) -> str:
    return f"""# Tutoriales

Esta carpeta es la ruta ejecutable y can\u00f3nica para aprender Agentic Systems 2.1.
Los notebooks ense\u00f1an la API p\u00fablica, no una segunda implementaci\u00f3n de la
librer\u00eda.

## Promesa de uso

    instalar -> configurar s\u00f3lo si hay frontera externa -> abrir -> Run All

Ning\u00fan notebook depende de celdas secretas. Los notebooks Python can\u00f3nicos
permanecen sin outputs; la evidencia se produce desde un kernel limpio.
RUN_*_LIVE=0 mantiene offline las fronteras externas sin fabricar evidencia.

## Modelo que ense\u00f1an

    Tool / Skill -> Agent -> System -> Environment -> Eval
                          |
                          +-> Provider (d\u00f3nde corre inferencia)
                          +-> Framework (qui\u00e9n controla el loop)
                          +-> RunResult (contrato de salida com\u00fan)

En los ejemplos, `toolkit` es el alias de todo el paquete `agentic_systems`;
`ToolSet` es s\u00f3lo un conjunto de Tools agrupadas bajo un namespace.

`toolkit.load_skill(path)` devuelve una Skill portable de Agentic Systems. Ese
formato re\u00fane instrucciones, Tools y contratos, pero no afirma que cualquier
carpeta de Skill de Claude/Anthropic o ChatGPT/OpenAI sea intercambiable sin un
adaptador expl\u00edcito.

Agent conserva su pipeline propio de una unidad de c\u00f3mputo. `toolkit.agent(...)`
crea un System m\u00ednimo interno s\u00f3lo para ownership, registros y defaults. System
compila un plan de ejecuci\u00f3n externo que conecta y ordena unidades. Environment
a\u00f1ade episodios y pasos; Eval mide Agent, System o cualquier Executable.

## Orden pedag\u00f3gico can\u00f3nico

El orden conserva la progresi\u00f3n de 1.1.3. Los cap\u00edtulos nuevos de 2.0 se
insertan donde aclaran Provider x Framework y cierran la trazabilidad 1:1.

| # | Notebook | Continuidad / evidencia |
|---:|---|---|
| 00 | providers/00_auto.ipynb | Runtime declarativo y resoluci\u00f3n auto. |
| 01 | providers/02_bedrock.ipynb | Runtime Bedrock por la fachada com\u00fan. |
| 02 | providers/01_openai.ipynb | Runtime OpenAI por la misma fachada. |
| 03 | core/00_runtime_scheduler.ipynb | Scheduler, retry y timeout. |
| 04 | providers/03_vllm.ipynb | Runtime vLLM OpenAI-compatible. |
| 05 | providers/04_ollama.ipynb | Runtime Ollama local OpenAI-compatible. |
| 06 | core/01_tool.ipynb | Tool, schemas y policy. |
| 07 | core/02_skills.ipynb | Skill nativa y carga desde filesystem. |
| 08 | core/03_agent.ipynb | Agent, contrato, pipeline y RunResult. |
| 09 | core/04_results_lineage.ipynb | Human result, composici\u00f3n y lineage. |
| 10 | frameworks/02_aws_strands.ipynb | Strands real: kwargs, hooks, MCP y A2A. |
| 11 | frameworks/01_openai_agents.ipynb | Integraci\u00f3n OpenAI Agents real. |
| 12 | frameworks/00_langgraph.ipynb | LangGraph como l\u00f3gica del Agent/System. |
| 13 | core/05_system.ipynb | Ownership, registros y compilaci\u00f3n. |
| 14 | core/06_graph_native.ipynb | Graph portable sin SDK externo. |
| 15 | core/07_environment_eval.ipynb | Episodios, pasos, rewards y Eval. |
| 16 | core/08_single_agentic_system.ipynb | Sistema de un Agent end-to-end. |
| 17 | core/09_multi_agentic_system.ipynb | Sistema secuencial de varios Agents. |
| 18 | core/10_multi_agent_graph.ipynb | Sistema multi-agent con Graph. |
| 19 | frameworks/03_provider_framework_matrix.ipynb | Matriz 5 x 4 y evidencia live. |
| 20 | api/14_api_contract_matrix.ipynb | Contrato Source/API/Docs/Pytest 1:1. |

## Capas, no rutas separadas

| Capa | Pregunta | Regla |
|---|---|---|
| core | \u00bfQu\u00e9 se construye y compone? | Python Runtime y Framework native. |
| providers | \u00bfD\u00f3nde corre inferencia? | Preflight; llamada externa s\u00f3lo si est\u00e1 habilitada. |
| frameworks | \u00bfQui\u00e9n controla el loop? | SDK real; Provider independiente. |
| api | \u00bfTodo lo publicado es trazable? | IDs exactos generados desde Source. |

El bloque A2A del tutorial Strands requiere la capacidad nativa opcional
declarada en `frameworks/requirements-strands-a2a.txt`. Se instala al preparar
el entorno, nunca desde una celda, para conservar kernels reproducibles.

### Superficies nativas ejercitadas

| Framework | Construcci\u00f3n (`agent_kwargs`) | Ejecuci\u00f3n (`run_kwargs`) | Capacidad distintiva |
|---|---|---|---|
| native | No aplica | No aplica | Contrato portable de Agentic Systems. |
| LangGraph | La topolog\u00eda se declara con `toolkit.graph` | La ejecuci\u00f3n se observa v\u00eda `GraphApp` | Estado y rutas condicionales reales. |
| OpenAI Agents | Guardrails y handoffs | `SQLiteSession` | Runner, sesi\u00f3n y handoff nativos. |
| Strands | Hooks, Tools nativas, clientes MCP y A2A | Structured output | Lifecycle y protocolos nativos. |

La matriz Provider \u00d7 Framework mantiene los kwargs vac\u00edos intencionalmente: su
objetivo es medir sustituibilidad. Los notebooks individuales prueban las
capacidades distintivas sin contaminar esa comparaci\u00f3n.

## Auto, provider expl\u00edcito y credenciales

Los notebooks espec\u00edficos de Provider son expl\u00edcitos: OpenAI, Bedrock,
vLLM u Ollama. Los notebooks de Framework usan python-runtime offline; al activar
live, auto elige el primer Provider listo seg\u00fan prioridad. La matriz 5 x 4 usa
cada Provider de forma expl\u00edcita para que ninguna combinaci\u00f3n quede oculta.

| Frontera | Configuraci\u00f3n | Opt-out |
|---|---|---|
| OpenAI | OPENAI_API_KEY; OPENAI_MODEL opcional | RUN_OPENAI_LIVE=0 |
| Bedrock | regi\u00f3n y cadena AWS o AWS_BEARER_TOKEN_BEDROCK | RUN_BEDROCK_LIVE=0 |
| vLLM | VLLM_BASE_URL y VLLM_MODEL | RUN_VLLM_LIVE=0 |
| Ollama | OLLAMA_MODEL; OLLAMA_BASE_URL opcional | RUN_OLLAMA_LIVE=0 |
| Matriz | RUN_MATRIX_LIVE=1 y Providers listos | RUN_MATRIX_LIVE=0 |

No pegues secretos en notebooks. Un caso no ejecutado se reporta como not-run
con motivo; nunca cuenta como passed. Un error live de credenciales, permisos,
modelo o endpoint permanece visible.

La matriz distingue estados que no deben confundirse:

| Estado | Significado |
|---|---|
| declared | La combinaci\u00f3n pertenece al contrato 5 x 4. |
| ready | Su configuraci\u00f3n y dependencias superaron el preflight. |
| not-run | No cruz\u00f3 la frontera externa; incluye el motivo y no cuenta como \u00e9xito. |
| passed | Se ejecut\u00f3 y sus invariantes fueron comprobados. |
| failed | Se ejecut\u00f3 y preserva el error real. |

## Contrato de salida y narrativa

Cada demostraci\u00f3n declara objetivo, par\u00e1metros editables, construcci\u00f3n,
ejecuci\u00f3n o `not-run` expl\u00edcito, resultado e interpretaci\u00f3n y `api_coverage`.
La igualdad de `RunResult` significa el mismo esquema p\u00fablico y los mismos
invariantes en toda combinaci\u00f3n; no significa que `data`, `final`,
`native_result`, `messages`, `usage`, `meta` o el objeto del SDK sean id\u00e9nticos.
Los notebooks no fabrican resultados ni mutan sus campos para aparentar \u00e9xito.

## Gate de release

Los 21 notebooks Python deben importar agentic_systems as toolkit, usar s\u00f3lo
la API p\u00fablica estable, compilar, comenzar sin outputs y declarar metadata.
La suite los ejecuta desde kernels limpios: 17 producen evidencia determinista
y 4 prueban not-run de Providers. El notebook API verifica
{manifest["entry_count"]} IDs y {manifest["scenario_count"]} escenarios compartidos.

## Contribution Standard

Every notebook must state its goal, editable inputs, ownership model, public API
construction, execution or explicit not-run, result interpretation and literal
api_coverage. Run All must not depend on hidden cells or fabricated results.

Tutorial fixtures may contain small domain callbacks, but must not import
package internals or duplicate provider/framework behavior. The canonical
grammar is toolkit.tool(...), toolkit.skill(...), toolkit.agent(...),
toolkit.system(...), toolkit.graph(...), toolkit.environment(...) and
toolkit.eval(...).
"""


def _outputs() -> dict[Path, str]:
    manifest = toolkit.api_contract()
    return {
        API_DOC: _api_doc(API_DOC.read_text(encoding="utf-8"), manifest),
        CONTRACT_DOC: _contract_doc(manifest),
        CONTRACT_NOTEBOOK: _notebook(manifest),
        TUTORIAL_README: _tutorial_readme(manifest),
    }


def generate(*, check: bool) -> int:
    drift: list[Path] = []
    for path, content in _outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            drift.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"generated {path.relative_to(ROOT)}")
    if drift:
        print("API contract drift:")
        for path in drift:
            print(f"- {path}")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    return generate(check=parser.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
